# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-07 20:01
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='due',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), max_digits=20, null=True),
        ),
    ]
