# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-07 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_event_venue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='advance',
            new_name='paid',
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Booked', max_length=30),
        ),
    ]
