# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-07 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20161108_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='service',
        ),
    ]
