# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-07 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_remove_event_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='service.Event'),
            preserve_default=False,
        ),
    ]
