# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-07 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=40, null=True)),
                ('last_name', models.CharField(blank=True, max_length=40, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=10, null=True)),
                ('business_name', models.CharField(max_length=40)),
                ('street_name', models.CharField(blank=True, max_length=40)),
                ('town', models.CharField(blank=True, max_length=40)),
                ('district', models.CharField(blank=True, max_length=40)),
                ('pin_code', models.CharField(blank=True, max_length=6)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
